services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - huggingface_cache:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    command: ["npm", "run", "dev", "--", "--host"]
volumes:
  huggingface_cache:
